### ISSUE TITLE
Aperture Regions not working

### ISSUE THREAD

**Issue by vanpattenh** [PaloAltoNetworks/Splunk-Apps#115]
The Region configuration of Add-on does not seem to work.  When you edit an Input object, the Region is always empty/forgotten.
  -- Tried to manually add region = us into the inputs.conf file without any success
  -- See errors in extract below...
  -- Modified the input_module_aperture.py script with region = "us" and the add-on now works.

-------   Section of script with static value added (in 2 locations)...
    region = helper.get_arg('region')
    region = "us"
    url_domain = REGION_DOMAIN[region]

-------   Extract from splunk_ta_paloalto_aperture.log
2019-01-23 12:37:32,299 ERROR pid=5324 tid=MainThread file=base_modinput.py:log_error:307 | Get error when collecting events.
Traceback (most recent call last):
  File "C:\Program Files\Splunk\etc\apps\Splunk_TA_paloalto\bin\splunk_ta_paloalto\modinput_wrapper\base_modinput.py", line 127, in stream_events
    self.collect_events(ew)
  File "C:\Program Files\Splunk\etc\apps\Splunk_TA_paloalto\bin\aperture.py", line 64, in collect_events
    input_module.collect_events(self, ew)
  File "C:\Program Files\Splunk\etc\apps\Splunk_TA_paloalto\bin\input_module_aperture.py", line 78, in collect_events
    url_domain = REGION_DOMAIN[region]
KeyError: None

**Comment by paulmnguyen** [comment]
Closing this bug. This has been tested and I can confirm the region is being saved.
