### ISSUE TITLE
Palo Alto Networks Add-On: TypeError: '>=' not supported between instances of 'HTTPError' and 'int'

### ISSUE THREAD

**Issue by christiaanvaken** [PaloAltoNetworks/Splunk-Apps#288]
We have installed the Palo Alto Networks Add-On and have created an input for Cortex XDR. Our index _internal shows a lot of errors from this add-on:

```
 Get error when collecting events.
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/modular_input/checkpointer.py", line 218, in get
    record = self._collection_data.query_by_id(key)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/splunklib/client.py", line 3790, in query_by_id
    return json.loads(self._get(UrlEncoded(str(id), encode_slash=True)).body.read().decode('utf-8'))
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/splunklib/client.py", line 3755, in _get
    return self.service.get(self.path + url, owner=self.owner, app=self.app, sharing=self.sharing, **kwargs)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/splunklib/binding.py", line 291, in wrapper
    return request_fun(self, *args, **kwargs)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/splunklib/binding.py", line 72, in new_f
    val = f(*args, **kwargs)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/splunklib/binding.py", line 697, in get
    response = self.http.get(path, all_headers, **query)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/splunklib/binding.py", line 1230, in get
    return self.request(url, { 'method': "GET", 'headers': headers })
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/splunklib/binding.py", line 1302, in request
    raise HTTPError(response)
solnlib.packages.splunklib.binding.HTTPError: HTTP 503 Service Unavailable -- KV Store is disabled.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/modinput_wrapper/base_modinput.py", line 128, in stream_events
    self.collect_events(ew)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/cortex_xdr.py", line 76, in collect_events
    input_module.collect_events(self, ew)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/input_module_cortex_xdr.py", line 173, in collect_events
    mod_time = get_mod_time(helper)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/input_module_cortex_xdr.py", line 38, in get_mod_time
    latest_modification_time = helper.get_check_point("latest_incident_modified")
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/modinput_wrapper/base_modinput.py", line 521, in get_check_point
    return self.ckpt.get(key)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/utils.py", line 159, in wrapper
    return func(*args, **kwargs)
  File "/opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/modular_input/checkpointer.py", line 222, in get
    'Get checkpoint failed: %s.', traceback.format_exc(e))
  File "/opt/splunk/lib/python3.7/traceback.py", line 167, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/opt/splunk/lib/python3.7/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/opt/splunk/lib/python3.7/traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "/opt/splunk/lib/python3.7/traceback.py", line 337, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'HTTPError' and 'int'
```

Because of this error, no logging is received. It is configured on a Splunk Heavy Forwarder.

**Comment by christiaanvaken** [comment]
Problem is already solved by enabling the KV store.
